[package]
name = "ecocode"
version = "0.1.0"
edition = "2024"
description = "EcoCode is a system to analyze your code energy and cost efficiency."


[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
sysinfo = "0.38.0"
